# Generated by Django 4.0.4 on 2022-04-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='time',
        ),
        migrations.AddField(
            model_name='available',
            name='time',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TimeRange',
        ),
    ]
